config/routes.rb
Rails.application.routes.draw do

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do #onlyオプションを使用して必要なroutingだけを生成
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, :email, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end

  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    #@blog = Blog.find(params[:id])
    #@blog.update(blogs_params)
    #redirect_to blogs_path
    @blog = Blog.find(params[:id])
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "ブログを更新しました！"
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end
  
  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/concerns/old/20170611contacts_controller.rb
class ContactsController < ApplicationController
  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
      redirect_to new_contact_path, notice: "お問い合わせ頂き誠にありがとうございます！"
    else
      render action: 'new'
    end
  end
  
  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :email,:content)
    end
end
#  def create
#  end

#  def new
#  end

#  def create
#  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
      redirect_to root_path, notice: "お問い合わせが完了しました！"
    else
      render action: 'new'
    end
  end
  
  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :email,:content)
    end
end
#  def create
#  end

#  def new
#  end

#  def create
#  end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
 def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
 end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :タイトル %>
<%= f.text_field :title, class: 'form-control' %>
<br>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ブログ一覧</h1>
      <%= link_to "ブログを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
  <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/old/20170611new.html.erb
<p id="notice"><%= notice %></p>

<h4>ブログを作成する</h4>

<%= render 'form' %>

app/views/blogs/old/20170618index.html.1.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ブログ一覧</h1>
      <%= link_to "ブログを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/old/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/old/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@blog) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/old/index.html.erb
<p><%= notice %></p>

<h1>ブログ一覧</h1>

<% @blogs.each do |blog| %>
  <p>タイトル:<%= blog.title %></p>
  <p>本文:<%= blog.content %></p>
  <%= link_to "ブログを編集する", edit_blog_path(blog.id) %>
  <%= link_to "ブログを削除する", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %>
<% end %>

<%= link_to "ブログを作成する", new_blog_path %>

app/views/blogs/old/oldedit.html.erb
<p id="notice"><%= notice %></p>

<h4>ブログを編集する</h4>

<%= render 'form' %>

app/views/blogs/old/oldnew.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name , class: 'form-control' %>
  <%= f.hidden_field :email , class: 'form-control'  %>
　<%= f.hidden_field :content , class: 'form-control'  %>
  <p>Name:<%= @contact.name %></p>
  <p>Email:<%= @contact.email %></p>
　<p>Content:<%= @contact.content %></p>
  <%= f.submit "送信する" ,class: 'btn btn-primary btn-block'  %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name , class: 'form-control'  %>
  <%= f.hidden_field :email , class: 'form-control'  %>
　<%= f.hidden_field :content , class: 'form-control'  %>
  <%= f.submit "もどる" ,class: 'btn btn-primary btn-block' , name: 'back'%>
<% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<p id="notice"><%= notice %></p>
    <% if @contact.errors.any? %>
        <div id="error_explanation">
            <h3><%= @contact.errors.count %>件のエラーがあります。</h3>
            <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>    
        </div>
    <% end %>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control' %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>
    </div>
</div>

app/views/contacts/old/20170611confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
　<%= f.hidden_field :content %>
  <p>Name:<%= @contact.name %></p>
  <p>Email:<%= @contact.email %></p>
　<p>Content:<%= @contact.content %></p>
  <%= f.submit "送信する" %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
　<%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/contacts/old/20170611new.html.erb
<p id="notice"><%= notice %></p>
    <% if @contact.errors.any? %>
        <div id="error_explanation">
            <h3><%= @contact.errors.count %>件のエラーがあります。</h3>
            <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>    
        </div>
    <% end %>    

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Achieve", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "お問い合わせ", new_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "ブログ", blogs_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/layouts/old/20170618application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "Achieve", root_path %></li>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "お問い合わせ", new_contact_path %></li>
      <li><%= link_to "ブログ", blogs_path %></li>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<header>
<font size="5" font color="fffffff"><%= notice %></font>
</header>
<section class="main-header">
 <img src="<%= asset_path "achieve.png" %>">
</section>
<section class="about">
  <h1>About Achieve</h1>
  <p>
     Achieveは、受講生のために作成された、教材用アプリです。<br>
     Achieveを作り終えることで、SecondTeamに参加するための力を身につけることができます。
  </p>
  <p>
     Acheiveを一言で表すと、タスク管理アプリです。<br>
     チームメンバーが、今どのようなタスクを行っているかリアルタイムで把握することができます。
  </p>
</section>
  <section class="function container-fluid">
    <div class="row">
    <h2>Function</h2>
      <div class="function-images">
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "key.png" %>">
            <p>ログイン機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "mails.png" %>">
            <p>メール送信機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "girls.png" %>">
            <p>友達つながり機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "comment.png" %>">
            <p>コメント投稿機能</p>
          </div>
        </div>
      </div>
    </div>
    <div id="page-top-btn" class="page-top-btn">
      <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
  </section>
<footer>
</footer>